version: '3.8'

services:
  sam-autolabel:
    build: .
    image: sam-autolabel:latest
    container_name: sam_autolabel_dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace
      - /mnt/b/cd_p/bmt_demo/test_yolo/dataset:/workspace/storage  # 데이터셋용 외부 마운트 (필요시 유지/수정)
    ports:
      - "8889:8888"  # Jupyter
    shm_size: '8gb'
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: /bin/bash
